sonar.projectKey=aceest-fitness-gym
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/test-results.xml

sonar.exclusions=**/__pycache__/**,**/migrations/**
sonar.coverage.exclusions=tests/**,**/__pycache__/**